### ISSUE TITLE
move into the Hub?

### ISSUE THREAD

**Issue by afeld** [18F/archived-guides#4]
This seems a bit too small to be a standalone site, and it would be nice for the guide names to come up in Hub search anyway. Thoughts?

**Comment by mbland** [comment]
Wow, just noticed this after forever... The horse is out of the barn when it comes to [18F Pages](https://github.com/18F/pages) as a microsite publishing platform, but I think we _could_ possibly add the [`jekyll_pages_api`](https://github.com/18F/jekyll_pages_api) and [`jekyll_pages_api_search`](https://github.com/18F/jekyll_pages_api_search) gems and find a way to stitch individual guide indices into the Hub's index.

_Or_--get this, wait for it--we could have a standalone site that consumes all the `api/v1/pages.json` files and runs `jekyll_pages_api_search` to produce a master index that the Hub could then import. Thoughts?

**Comment by jessieay** [comment]
I like this idea! I am not yet very familiar with how 18F Pages works, but one solution would be to just move the content of this repo over to the `hub` repo, right?

**Comment by mbland** [comment]
Guides is supposed to be the public-facing landing page for a whole set of separate sites; not sure it makes sense for it to be moved directly into the Hub, since it has a different look, a different URL structure, and a slightly different publishing model. Part of the idea is that other teams can fork our Pages and Guides repos and run with them without having to fork the Hub (cool as that may be).

That said, my mind isn't completely closed to the idea.

**Comment by gbinal** [comment]
Fwiw, I'm a +1 to keeping guides distinct.

**Comment by afeld** [comment]
K, thanks folks.
